//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordResetAPI.SMServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.hp.com/SM/7", ConfigurationName="SMServiceRef.PassResetOperator")]
    public interface PassResetOperator {
        
        // CODEGEN: Generating message contract since the operation RetrievePassResetOperator is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Retrieve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorResponse1 RetrievePassResetOperator(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Retrieve", ReplyAction="*")]
        System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorResponse1> RetrievePassResetOperatorAsync(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest1 request);
        
        // CODEGEN: Generating message contract since the operation RetrievePassResetOperatorKeysList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="RetrieveKeysList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListResponse1 RetrievePassResetOperatorKeysList(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RetrieveKeysList", ReplyAction="*")]
        System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListResponse1> RetrievePassResetOperatorKeysListAsync(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation RetrievePassResetOperatorList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="RetrieveList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListResponse1 RetrievePassResetOperatorList(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="RetrieveList", ReplyAction="*")]
        System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListResponse1> RetrievePassResetOperatorListAsync(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation SavePassResetOperator is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PasswordResetAPI.SMServiceRef.SavePassResetOperatorResponse1 SavePassResetOperator(PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Save", ReplyAction="*")]
        System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.SavePassResetOperatorResponse1> SavePassResetOperatorAsync(PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrievePassResetOperatorRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PassResetOperatorModelType modelField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private bool updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        public RetrievePassResetOperatorRequest() {
            this.ignoreEmptyElementsField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PassResetOperatorModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
                this.RaisePropertyChanged("attachmentInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
                this.RaisePropertyChanged("attachmentInfoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
                this.RaisePropertyChanged("attachmentData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
                this.RaisePropertyChanged("attachmentDataSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
                this.RaisePropertyChanged("ignoreEmptyElements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
                this.RaisePropertyChanged("updatecounter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
                this.RaisePropertyChanged("updatecounterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
                this.RaisePropertyChanged("handle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7")]
    public partial class PassResetOperatorModelType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PassResetOperatorKeysType keysField;
        
        private PassResetOperatorInstanceType instanceField;
        
        private MessageType[] messagesField;
        
        private string queryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PassResetOperatorKeysType keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
                this.RaisePropertyChanged("keys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PassResetOperatorInstanceType instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
                this.RaisePropertyChanged("instance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7")]
    public partial class PassResetOperatorKeysType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StringType userNameField;
        
        private string queryField;
        
        private long updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public StringType UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
                this.RaisePropertyChanged("updatecounter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
                this.RaisePropertyChanged("updatecounterSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class StringType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private bool mandatoryField;
        
        private bool mandatoryFieldSpecified;
        
        private bool readonlyField;
        
        private bool readonlyFieldSpecified;
        
        private string valueField;
        
        public StringType() {
            this.typeField = "String";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
                this.RaisePropertyChanged("mandatory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mandatorySpecified {
            get {
                return this.mandatoryFieldSpecified;
            }
            set {
                this.mandatoryFieldSpecified = value;
                this.RaisePropertyChanged("mandatorySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @readonly {
            get {
                return this.readonlyField;
            }
            set {
                this.readonlyField = value;
                this.RaisePropertyChanged("readonly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readonlySpecified {
            get {
                return this.readonlyFieldSpecified;
            }
            set {
                this.readonlyFieldSpecified = value;
                this.RaisePropertyChanged("readonlySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class AttachmentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentTypeField;
        
        private string hrefField;
        
        private string contentIdField;
        
        private string actionField;
        
        private string nameField;
        
        private string typeField;
        
        private int lenField;
        
        private bool lenFieldSpecified;
        
        private string charsetField;
        
        private string uploadbyField;
        
        private string uploaddateField;
        
        private string attachmentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/2005/05/xmlmime")]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
                this.RaisePropertyChanged("href");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
                this.RaisePropertyChanged("contentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int len {
            get {
                return this.lenField;
            }
            set {
                this.lenField = value;
                this.RaisePropertyChanged("len");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lenSpecified {
            get {
                return this.lenFieldSpecified;
            }
            set {
                this.lenFieldSpecified = value;
                this.RaisePropertyChanged("lenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string charset {
            get {
                return this.charsetField;
            }
            set {
                this.charsetField = value;
                this.RaisePropertyChanged("charset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("upload.by")]
        public string uploadby {
            get {
                return this.uploadbyField;
            }
            set {
                this.uploadbyField = value;
                this.RaisePropertyChanged("uploadby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("upload.date")]
        public string uploaddate {
            get {
                return this.uploaddateField;
            }
            set {
                this.uploaddateField = value;
                this.RaisePropertyChanged("uploaddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attachmentType {
            get {
                return this.attachmentTypeField;
            }
            set {
                this.attachmentTypeField = value;
                this.RaisePropertyChanged("attachmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7")]
    public partial class PassResetOperatorInstanceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StringType userNameField;
        
        private StringType emailField;
        
        private AttachmentType[] attachmentsField;
        
        private string queryField;
        
        private string uniquequeryField;
        
        private string recordidField;
        
        private long updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public StringType UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public StringType Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attachment", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public AttachmentType[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("attachments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uniquequery {
            get {
                return this.uniquequeryField;
            }
            set {
                this.uniquequeryField = value;
                this.RaisePropertyChanged("uniquequery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string recordid {
            get {
                return this.recordidField;
            }
            set {
                this.recordidField = value;
                this.RaisePropertyChanged("recordid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
                this.RaisePropertyChanged("updatecounter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
                this.RaisePropertyChanged("updatecounterSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class MessageType : StringType {
        
        private int severityField;
        
        private bool severityFieldSpecified;
        
        private string moduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool severitySpecified {
            get {
                return this.severityFieldSpecified;
            }
            set {
                this.severityFieldSpecified = value;
                this.RaisePropertyChanged("severitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
                this.RaisePropertyChanged("module");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrievePassResetOperatorResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PassResetOperatorModelType modelField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool moreField;
        
        private bool moreFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PassResetOperatorModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
                this.RaisePropertyChanged("schemaRevisionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
                this.RaisePropertyChanged("schemaRevisionLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
                this.RaisePropertyChanged("returnCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
                this.RaisePropertyChanged("handle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool more {
            get {
                return this.moreField;
            }
            set {
                this.moreField = value;
                this.RaisePropertyChanged("more");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moreSpecified {
            get {
                return this.moreFieldSpecified;
            }
            set {
                this.moreFieldSpecified = value;
                this.RaisePropertyChanged("moreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public enum StatusType {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        FAILURE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrievePassResetOperatorRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.hp.com/SM/7", Order=0)]
        public PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest RetrievePassResetOperatorRequest;
        
        public RetrievePassResetOperatorRequest1() {
        }
        
        public RetrievePassResetOperatorRequest1(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest RetrievePassResetOperatorRequest) {
            this.RetrievePassResetOperatorRequest = RetrievePassResetOperatorRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrievePassResetOperatorResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.hp.com/SM/7", Order=0)]
        public PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorResponse RetrievePassResetOperatorResponse;
        
        public RetrievePassResetOperatorResponse1() {
        }
        
        public RetrievePassResetOperatorResponse1(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorResponse RetrievePassResetOperatorResponse) {
            this.RetrievePassResetOperatorResponse = RetrievePassResetOperatorResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrievePassResetOperatorKeysListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PassResetOperatorModelType modelField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private bool updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        public RetrievePassResetOperatorKeysListRequest() {
            this.ignoreEmptyElementsField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PassResetOperatorModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
                this.RaisePropertyChanged("attachmentInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
                this.RaisePropertyChanged("attachmentInfoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
                this.RaisePropertyChanged("attachmentData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
                this.RaisePropertyChanged("attachmentDataSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
                this.RaisePropertyChanged("ignoreEmptyElements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
                this.RaisePropertyChanged("updatecounter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
                this.RaisePropertyChanged("updatecounterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
                this.RaisePropertyChanged("handle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrievePassResetOperatorKeysListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PassResetOperatorKeysType[] keysField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool moreField;
        
        private bool moreFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keys", Order=0)]
        public PassResetOperatorKeysType[] keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
                this.RaisePropertyChanged("keys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
                this.RaisePropertyChanged("schemaRevisionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
                this.RaisePropertyChanged("schemaRevisionLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
                this.RaisePropertyChanged("returnCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
                this.RaisePropertyChanged("handle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool more {
            get {
                return this.moreField;
            }
            set {
                this.moreField = value;
                this.RaisePropertyChanged("more");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moreSpecified {
            get {
                return this.moreFieldSpecified;
            }
            set {
                this.moreFieldSpecified = value;
                this.RaisePropertyChanged("moreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrievePassResetOperatorKeysListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.hp.com/SM/7", Order=0)]
        public PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest RetrievePassResetOperatorKeysListRequest;
        
        public RetrievePassResetOperatorKeysListRequest1() {
        }
        
        public RetrievePassResetOperatorKeysListRequest1(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest RetrievePassResetOperatorKeysListRequest) {
            this.RetrievePassResetOperatorKeysListRequest = RetrievePassResetOperatorKeysListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrievePassResetOperatorKeysListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.hp.com/SM/7", Order=0)]
        public PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListResponse RetrievePassResetOperatorKeysListResponse;
        
        public RetrievePassResetOperatorKeysListResponse1() {
        }
        
        public RetrievePassResetOperatorKeysListResponse1(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListResponse RetrievePassResetOperatorKeysListResponse) {
            this.RetrievePassResetOperatorKeysListResponse = RetrievePassResetOperatorKeysListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrievePassResetOperatorListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PassResetOperatorKeysType[] keysField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private bool updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        private long attachmentTypeField;
        
        private bool attachmentTypeFieldSpecified;
        
        public RetrievePassResetOperatorListRequest() {
            this.ignoreEmptyElementsField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keys", Order=0)]
        public PassResetOperatorKeysType[] keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
                this.RaisePropertyChanged("keys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
                this.RaisePropertyChanged("attachmentInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
                this.RaisePropertyChanged("attachmentInfoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
                this.RaisePropertyChanged("attachmentData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
                this.RaisePropertyChanged("attachmentDataSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
                this.RaisePropertyChanged("ignoreEmptyElements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
                this.RaisePropertyChanged("updatecounter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
                this.RaisePropertyChanged("updatecounterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
                this.RaisePropertyChanged("handle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long attachmentType {
            get {
                return this.attachmentTypeField;
            }
            set {
                this.attachmentTypeField = value;
                this.RaisePropertyChanged("attachmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentTypeSpecified {
            get {
                return this.attachmentTypeFieldSpecified;
            }
            set {
                this.attachmentTypeFieldSpecified = value;
                this.RaisePropertyChanged("attachmentTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class RetrievePassResetOperatorListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PassResetOperatorInstanceType[] instanceField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool moreField;
        
        private bool moreFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instance", Order=0)]
        public PassResetOperatorInstanceType[] instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
                this.RaisePropertyChanged("instance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
                this.RaisePropertyChanged("schemaRevisionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
                this.RaisePropertyChanged("schemaRevisionLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
                this.RaisePropertyChanged("returnCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
                this.RaisePropertyChanged("handle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool more {
            get {
                return this.moreField;
            }
            set {
                this.moreField = value;
                this.RaisePropertyChanged("more");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moreSpecified {
            get {
                return this.moreFieldSpecified;
            }
            set {
                this.moreFieldSpecified = value;
                this.RaisePropertyChanged("moreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrievePassResetOperatorListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.hp.com/SM/7", Order=0)]
        public PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest RetrievePassResetOperatorListRequest;
        
        public RetrievePassResetOperatorListRequest1() {
        }
        
        public RetrievePassResetOperatorListRequest1(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest RetrievePassResetOperatorListRequest) {
            this.RetrievePassResetOperatorListRequest = RetrievePassResetOperatorListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrievePassResetOperatorListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.hp.com/SM/7", Order=0)]
        public PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListResponse RetrievePassResetOperatorListResponse;
        
        public RetrievePassResetOperatorListResponse1() {
        }
        
        public RetrievePassResetOperatorListResponse1(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListResponse RetrievePassResetOperatorListResponse) {
            this.RetrievePassResetOperatorListResponse = RetrievePassResetOperatorListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class SavePassResetOperatorRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PassResetOperatorModelType modelField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private long updateconstraintField;
        
        public SavePassResetOperatorRequest() {
            this.ignoreEmptyElementsField = true;
            this.updateconstraintField = ((long)(-1));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PassResetOperatorModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
                this.RaisePropertyChanged("attachmentInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
                this.RaisePropertyChanged("attachmentInfoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
                this.RaisePropertyChanged("attachmentData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
                this.RaisePropertyChanged("attachmentDataSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
                this.RaisePropertyChanged("ignoreEmptyElements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "-1")]
        public long updateconstraint {
            get {
                return this.updateconstraintField;
            }
            set {
                this.updateconstraintField = value;
                this.RaisePropertyChanged("updateconstraint");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class SavePassResetOperatorResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PassResetOperatorModelType modelField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PassResetOperatorModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
                this.RaisePropertyChanged("schemaRevisionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
                this.RaisePropertyChanged("schemaRevisionLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
                this.RaisePropertyChanged("returnCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePassResetOperatorRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.hp.com/SM/7", Order=0)]
        public PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest SavePassResetOperatorRequest;
        
        public SavePassResetOperatorRequest1() {
        }
        
        public SavePassResetOperatorRequest1(PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest SavePassResetOperatorRequest) {
            this.SavePassResetOperatorRequest = SavePassResetOperatorRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePassResetOperatorResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.hp.com/SM/7", Order=0)]
        public PasswordResetAPI.SMServiceRef.SavePassResetOperatorResponse SavePassResetOperatorResponse;
        
        public SavePassResetOperatorResponse1() {
        }
        
        public SavePassResetOperatorResponse1(PasswordResetAPI.SMServiceRef.SavePassResetOperatorResponse SavePassResetOperatorResponse) {
            this.SavePassResetOperatorResponse = SavePassResetOperatorResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PassResetOperatorChannel : PasswordResetAPI.SMServiceRef.PassResetOperator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassResetOperatorClient : System.ServiceModel.ClientBase<PasswordResetAPI.SMServiceRef.PassResetOperator>, PasswordResetAPI.SMServiceRef.PassResetOperator {
        
        public PassResetOperatorClient() {
        }
        
        public PassResetOperatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassResetOperatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassResetOperatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassResetOperatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorResponse1 PasswordResetAPI.SMServiceRef.PassResetOperator.RetrievePassResetOperator(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest1 request) {
            return base.Channel.RetrievePassResetOperator(request);
        }
        
        public PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorResponse RetrievePassResetOperator(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest RetrievePassResetOperatorRequest) {
            PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest1 inValue = new PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest1();
            inValue.RetrievePassResetOperatorRequest = RetrievePassResetOperatorRequest;
            PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorResponse1 retVal = ((PasswordResetAPI.SMServiceRef.PassResetOperator)(this)).RetrievePassResetOperator(inValue);
            return retVal.RetrievePassResetOperatorResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorResponse1> PasswordResetAPI.SMServiceRef.PassResetOperator.RetrievePassResetOperatorAsync(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest1 request) {
            return base.Channel.RetrievePassResetOperatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorResponse1> RetrievePassResetOperatorAsync(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest RetrievePassResetOperatorRequest) {
            PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest1 inValue = new PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorRequest1();
            inValue.RetrievePassResetOperatorRequest = RetrievePassResetOperatorRequest;
            return ((PasswordResetAPI.SMServiceRef.PassResetOperator)(this)).RetrievePassResetOperatorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListResponse1 PasswordResetAPI.SMServiceRef.PassResetOperator.RetrievePassResetOperatorKeysList(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest1 request) {
            return base.Channel.RetrievePassResetOperatorKeysList(request);
        }
        
        public PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListResponse RetrievePassResetOperatorKeysList(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest RetrievePassResetOperatorKeysListRequest) {
            PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest1 inValue = new PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest1();
            inValue.RetrievePassResetOperatorKeysListRequest = RetrievePassResetOperatorKeysListRequest;
            PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListResponse1 retVal = ((PasswordResetAPI.SMServiceRef.PassResetOperator)(this)).RetrievePassResetOperatorKeysList(inValue);
            return retVal.RetrievePassResetOperatorKeysListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListResponse1> PasswordResetAPI.SMServiceRef.PassResetOperator.RetrievePassResetOperatorKeysListAsync(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest1 request) {
            return base.Channel.RetrievePassResetOperatorKeysListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListResponse1> RetrievePassResetOperatorKeysListAsync(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest RetrievePassResetOperatorKeysListRequest) {
            PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest1 inValue = new PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorKeysListRequest1();
            inValue.RetrievePassResetOperatorKeysListRequest = RetrievePassResetOperatorKeysListRequest;
            return ((PasswordResetAPI.SMServiceRef.PassResetOperator)(this)).RetrievePassResetOperatorKeysListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListResponse1 PasswordResetAPI.SMServiceRef.PassResetOperator.RetrievePassResetOperatorList(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest1 request) {
            return base.Channel.RetrievePassResetOperatorList(request);
        }
        
        public PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListResponse RetrievePassResetOperatorList(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest RetrievePassResetOperatorListRequest) {
            PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest1 inValue = new PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest1();
            inValue.RetrievePassResetOperatorListRequest = RetrievePassResetOperatorListRequest;
            PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListResponse1 retVal = ((PasswordResetAPI.SMServiceRef.PassResetOperator)(this)).RetrievePassResetOperatorList(inValue);
            return retVal.RetrievePassResetOperatorListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListResponse1> PasswordResetAPI.SMServiceRef.PassResetOperator.RetrievePassResetOperatorListAsync(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest1 request) {
            return base.Channel.RetrievePassResetOperatorListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListResponse1> RetrievePassResetOperatorListAsync(PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest RetrievePassResetOperatorListRequest) {
            PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest1 inValue = new PasswordResetAPI.SMServiceRef.RetrievePassResetOperatorListRequest1();
            inValue.RetrievePassResetOperatorListRequest = RetrievePassResetOperatorListRequest;
            return ((PasswordResetAPI.SMServiceRef.PassResetOperator)(this)).RetrievePassResetOperatorListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PasswordResetAPI.SMServiceRef.SavePassResetOperatorResponse1 PasswordResetAPI.SMServiceRef.PassResetOperator.SavePassResetOperator(PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest1 request) {
            return base.Channel.SavePassResetOperator(request);
        }
        
        public PasswordResetAPI.SMServiceRef.SavePassResetOperatorResponse SavePassResetOperator(PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest SavePassResetOperatorRequest) {
            PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest1 inValue = new PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest1();
            inValue.SavePassResetOperatorRequest = SavePassResetOperatorRequest;
            PasswordResetAPI.SMServiceRef.SavePassResetOperatorResponse1 retVal = ((PasswordResetAPI.SMServiceRef.PassResetOperator)(this)).SavePassResetOperator(inValue);
            return retVal.SavePassResetOperatorResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.SavePassResetOperatorResponse1> PasswordResetAPI.SMServiceRef.PassResetOperator.SavePassResetOperatorAsync(PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest1 request) {
            return base.Channel.SavePassResetOperatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<PasswordResetAPI.SMServiceRef.SavePassResetOperatorResponse1> SavePassResetOperatorAsync(PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest SavePassResetOperatorRequest) {
            PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest1 inValue = new PasswordResetAPI.SMServiceRef.SavePassResetOperatorRequest1();
            inValue.SavePassResetOperatorRequest = SavePassResetOperatorRequest;
            return ((PasswordResetAPI.SMServiceRef.PassResetOperator)(this)).SavePassResetOperatorAsync(inValue);
        }
    }
}
